const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_alice11.png',
      normal2: 'novels/image_alice12.png',
      normal3: 'novels/image_alice13.png',
      normal4: 'novels/image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_nefa01.png',
      normal2: 'novels/image_nefa02.png',
      normal3: 'novels/image_nefa03.png',
      normal4: 'novels/image_nefa04.png',
      normal5: 'novels/image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'novels/back21.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い　良い　良い\n良い　良い　良い　良い' },
  { speaker: 'ニーファ', portrait: 'normal4', text: '乙女機能インストール中・・・ピピピ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'プププ\n' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'ポポポ' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'ガシャガシャ' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'ドキンドキン' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'インストール完了' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '全ての乙女機能のインストールが完了' },
  { speaker: '有栖', portrait: 'normal1', text: 'さて、どうなる？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'その前に一つ' },
  { speaker: '有栖', portrait: 'normal1', text: '何？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'エリカって、' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '有栖でしょ' },
  { speaker: '有栖', portrait: 'normal1', text: '・・・・・。' },
  { speaker: '有栖', portrait: 'normal2', text: 'バレたか' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'でも、居たんでしょ？' },
  { speaker: '有栖', portrait: 'normal1', text: '居たよ' },
  { speaker: '有栖', portrait: 'normal2', text: '傷ついた私' },
  { speaker: '有栖', portrait: 'normal1', text: '前を向きたかった私' },
  { speaker: '有栖', portrait: 'normal2', text: '諦めたくなかった私' },
  { speaker: '有栖', portrait: 'normal1', text: '強くなったと思っただけ、' },
  { speaker: '有栖', portrait: 'normal2', text: '少しずつ消えていった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '役目を終えたんだね' },
  { speaker: '有栖', portrait: 'normal3', text: 'そうなのかな' },
  { command: 'fadeout' },
  { command: 'hide_all' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'dialog_hide' },
  { command: 'background', value: 'novels/back22.jpg' },
  { command: 'se', value: 'gogogo.wav' },
  { command: 'wait', duration: 2000 },
  { command: 'fadein' },
  { speaker: '有栖', portrait: 'normal1', text: '戻ってきたわね' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '戻れなくなるかも' },
  { speaker: '有栖', portrait: 'normal1', text: '今更でしょ' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '怖い？' },
  { speaker: '有栖', portrait: 'normal1', text: 'なんでかな' },
  { speaker: '有栖', portrait: 'normal2', text: 'あんまり怖くない' },
  { speaker: '有栖', portrait: 'normal3', text: 'エリカが居るみたい' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '進もう！' },
  { speaker: '有栖', portrait: 'normal1', text: 'うん！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 30,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=30',
});

NovelEngine.play(SCRIPT);