const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_alice11.png',
      normal2: 'image_alice12.png',
      normal3: 'image_alice13.png',
      normal4: 'image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_nefa01.png',
      normal2: 'image_nefa02.png',
      normal3: 'image_nefa03.png',
      normal4: 'image_nefa04.png',
      normal5: 'image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg11.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い' },
  { speaker: 'ニーファ', portrait: 'normal4', text: '乙女機能インストール中・・・ピピピ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'プププ\n' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'ポポポ' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'インストール完了' },
  { speaker: '有栖', portrait: 'normal1', text: 'ねぇ、全部集まったら終わり？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'あと２個' },
  { speaker: '有栖', portrait: 'normal1', text: '教えてくれないんだ' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '次は決断の話を聞きたい' },
  { speaker: '有栖', portrait: 'normal1', text: '決断・・・' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '留学したことかな' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '不安だった？' },
  { speaker: '有栖', portrait: 'normal2', text: '最初はね' },
  { speaker: '有栖', portrait: 'normal2', text: 'とっても' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'じゃあ、どうして？' },
  { speaker: '有栖', portrait: 'normal1', text: 'エリカが言ってくれたんだ' },
  { speaker: '有栖', portrait: 'normal2', text: 'エリカに助けられてばっかり' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'なんて言ったの？' },
  { speaker: '有栖', portrait: 'normal1', text: '不安な道を選ぶんじゃなくて、' },
  { speaker: '有栖', portrait: 'normal2', text: '納得できる道を選ぶんだって' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'それで決めたの？' },
  { speaker: '有栖', portrait: 'normal1', text: 'うん' },
  { speaker: '有栖', portrait: 'normal2', text: '怖かったけど・・・' },
  { speaker: '有栖', portrait: 'normal1', text: 'あの日、飛行機に乗った瞬間、' },
  { speaker: '有栖', portrait: 'normal2', text: 'ワクワクもした' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '行ってよかった？' },
  { speaker: '有栖', portrait: 'normal1', text: '嫌なこともあったよ' },
  { speaker: '有栖', portrait: 'normal2', text: '言葉が上手く伝わらなかったり' },
  { speaker: '有栖', portrait: 'normal1', text: '自分だけ輪に入れなかったり' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'また、傷ついた？' },
  { speaker: '有栖', portrait: 'normal1', text: 'そうだね' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '行った意味はなかった？' },
  { speaker: '有栖', portrait: 'normal1', text: '少しずつだけど、自分から話しかけた' },
  { speaker: '有栖', portrait: 'normal2', text: '一歩だけ踏み出した' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '偉大なる一歩' },
  { speaker: '有栖', portrait: 'normal1', text: 'そしたらね' },
  { speaker: '有栖', portrait: 'normal2', text: '全部じゃないけど、' },
  { speaker: '有栖', portrait: 'normal3', text: '少しずつ変わっていった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '来た！' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '来た来た来た来た来たー！' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '審眼が来たーーー！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 28,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=28',
});

NovelEngine.play(SCRIPT);