const CHARACTERS = {
  alice: {
    name: 'アリス',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_alice01.png',
      normal2: 'image_alice02.png',
      normal3: 'image_alice03.png',
    },
  },
  flat: {
    name: 'フラット',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_flat01.png',
      normal2: 'image_flat02.png',
      normal3: 'image_flat03.png',
    },
  },
  crow: {
    name: 'カラス',
    position: 'right',
    defaultPortrait: 'normal',
    portraits: {
      normal1: 'image_crow01.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'back01.jpg' },
  { command: 'bgm', value: 'bgm01.mp3' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.0rem' },
  { command: 'show', character: 'alice', portrait: 'normal1' },
  { speaker: 'アリス', portrait: 'normal1', text: '大丈夫だった？' },
  { command: 'show', character: 'crow', portrait: 'normal1' },
  { speaker: 'カラス', portrait: 'normal1', text: 'ありがとう、見ての通り無事よ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'ここは密林なの？' },
  { speaker: 'カラス', portrait: 'normal1', text: 'ここの密林は妙なの。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'どこが妙なの？' },
  { speaker: 'カラス', portrait: 'normal1', text: '木が木のふりをしているの。' },
  { speaker: 'アリス', portrait: 'normal1', text: '木なんだから木のふりでいいじゃない。' },
  { speaker: 'カラス', portrait: 'normal1', text: 'それが妙なのよ。本物ほど偽物らしいものはないわ。' },
  { speaker: 'アリス', portrait: 'normal1', text: '聞けば聞くほど妙ね。' },
  { speaker: 'カラス', portrait: 'normal1', text: '今朝は密林が空を歩いていたの。' },
  { speaker: 'アリス', portrait: 'normal1', text: '密林は歩かないでしょう。' },
  { speaker: 'カラス', portrait: 'normal1', text: 'だから妙なの。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'わからないこと全部に「妙」をつけているだけじゃない？' },
  { speaker: 'カラス', portrait: 'normal1', text: 'そんな妙なことするかしら。' },
  { speaker: 'アリス', portrait: 'normal1', text: '今まさにしているわ。' },
  { speaker: 'カラス', portrait: 'normal1', text: 'ところで、密林と妙の違いは知ってる？' },
  { speaker: 'アリス', portrait: 'normal1', text: '知らないわ。' },
  { speaker: 'カラス', portrait: 'normal1', text: '密林は入るもの、妙は出られなくなるものよ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'ずいぶん前から妙の中にいるみたいね。' },
  { speaker: 'カラス', portrait: 'normal1', text: 'でも妙はカラスの真似をしている。' },
  { speaker: 'アリス', portrait: 'normal2', text: 'それは奇妙ね。' },
  { command: 'fadeout' },
  { command: 'hide_all' },
  { command: 'hide', character: 'alice' },
  { command: 'hide', character: 'crow' },
  { command: 'dialog_hide' },
  { command: 'background', value: 'back04.png', position: 'bottom' },
  { command: 'se', value: 'gogogo.wav' },
  { command: 'wait', duration: 2000 },
  { command: 'fadein' },
  { speaker: 'アリス', portrait: 'normal1', text: 'これが三つ目の星牢ね。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'もし私が誰かの夢なら、その人はずいぶん長い夢を見ているわね。' },
  { speaker: 'アリス', portrait: 'normal1', text: '起きる気がないのかしら。' },
  { speaker: 'アリス', portrait: 'normal1', text: '夢と幻の違いって、私にはわからないわ。' },
  { speaker: 'アリス', portrait: 'normal1', text: '不思議の国じゃ「わからない」という答えが、一番わかっている気がするわ。' },
  { speaker: 'アリス', portrait: 'normal2', text: '早く不思議の国に帰りたいわ。' },
  { command: 'wait', duration: 1000 },
  { command: 'show', character: 'flat', portrait: 'normal3' },
  { speaker: 'フラット', portrait: 'normal3', text: '（アリス・・・）' },
  { speaker: 'フラット', portrait: 'normal3', text: '（不思議の国に帰る方法は・・・）' },
  { command: 'hide', character: 'flat' },
  { command: 'dialog_hide' },
  { command: 'bg_scroll', direction: 'down', speed: 200, loop: false },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   'images/',
  bgmPath:     '../sounds/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  nextUrl:     '../index.html?select=1&storyStage=3',
});

NovelEngine.play(SCRIPT);