const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_alice11.png',
      normal2: 'novels/image_alice12.png',
      normal3: 'novels/image_alice13.png',
      normal4: 'novels/image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_nefa01.png',
      normal2: 'novels/image_nefa02.png',
      normal3: 'novels/image_nefa03.png',
      normal4: 'novels/image_nefa04.png',
      normal5: 'novels/image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg11.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い' },
  { speaker: 'ニーファ', portrait: 'normal4', text: '乙女機能インストール中・・・ピピピ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'プププ\n' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'ポポポ' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'インストール完了' },
  { speaker: '有栖', portrait: 'normal1', text: 'いよいよ、だね。' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'あと１個' },
  { speaker: '有栖', portrait: 'normal1', text: 'なんだか寂しいわね' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'まだ家に帰りたい？' },
  { speaker: '有栖', portrait: 'normal1', text: '帰りたい' },
  { speaker: '有栖', portrait: 'normal2', text: '帰れるかな' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '帰れるよ' },
  { speaker: '有栖', portrait: 'normal1', text: 'ありがと' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '有栖は強いよね' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '今までの話を聞いていると、' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '弱そうなのに' },
  { speaker: '有栖', portrait: 'normal1', text: '時間がなかったの' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '５６億年もあったのに？' },
  { speaker: '有栖', portrait: 'normal1', text: 'なにそれ\nそっか' },
  { speaker: '有栖', portrait: 'normal2', text: '人間は１００年くらいしか生きられないんだ' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '個としてはそうだね' },
  { speaker: '有栖', portrait: 'normal1', text: 'どういうこと？' },
  { speaker: '有栖', portrait: 'normal2', text: 'ま、いっか' },
  { speaker: '有栖', portrait: 'normal1', text: 'エリカ、病気だったんだ' },
  { speaker: '有栖', portrait: 'normal2', text: 'もう手遅れだった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '死んだ？' },
  { speaker: '有栖', portrait: 'normal1', text: '・・・・・。' },
  { speaker: '有栖', portrait: 'normal2', text: 'エリカが生きている間に強くならないと、' },
  { speaker: '有栖', portrait: 'normal1', text: '怖くても進まないと、' },
  { speaker: '有栖', portrait: 'normal2', text: '誰かを信じて、自分で選んで、' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '間に合った？' },
  { speaker: '有栖', portrait: 'normal1', text: 'どうかな' },
  { speaker: '有栖', portrait: 'normal2', text: 'でも、' },
  { speaker: '有栖', portrait: 'normal3', text: '全部、今も、私の中に残ってる' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '来た！' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '来た来た来た来た来たー！' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '時間が来たーーー！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 29,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=29',
});

NovelEngine.play(SCRIPT);