const CHARACTERS = {
  alice: {
    name: 'アリス',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_alice01.png',
      normal2: 'novels/image_alice02.png',
      normal3: 'novels/image_alice03.png',
    },
  },
  flat: {
    name: 'フラット',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_flat01.png',
      normal2: 'novels/image_flat02.png',
      normal3: 'novels/image_flat03.png',
      dest01: 'novels/image_flat04.png',
      dest02: 'novels/image_flat05.png',
    },
  },
  yomi: {
    name: 'ヨミ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_yomi01.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'novels/back01.jpg' },
  { command: 'bgm', value: 'bgm01.mp3' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'show', character: 'alice', portrait: 'normal1' },
  { speaker: 'アリス', portrait: 'normal1', text: 'あなたが最後の人なのね。' },
  { command: 'show', character: 'yomi', portrait: 'normal1' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '最後？' },
  { speaker: 'アリス', portrait: 'normal1', text: 'ええ。もうパーティーは終わりよ。' },
  { speaker: 'ヨミ', portrait: 'normal1', text: 'そう。なら、私もようやく帰れる。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'どこへ？' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '不思議の国よ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'え？' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '私の妹を知らない？\nすぐ首をはねたがる困った子。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'あなた、何者なの？' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '昔はスペードの女王と呼ばれていたわ。' },
  { speaker: 'アリス', portrait: 'normal2', text: 'そんな人いたかしら。' },
  { speaker: 'ヨミ', portrait: 'normal1', text: 'いなかったの。だから迷子になったのよ。' },
  { command: 'hide', character: 'yomi' },
  { speaker: 'フラット', portrait: 'dest01', text: 'ア・・・リスあ・・・りが・・・とう・・・。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'いままでどこにいたの？' },
  { command: 'bgm_fade', duration: 1000 },
  { command: 'show', character: 'flat', portrait: 'dest01' },
  { command: 'wait', duration: 1000 },
  { command: 'bgm', value: 'SND_05_flat.mp3' },
  { speaker: 'フラット', portrait: 'dest01', text: '・・・・・。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'ってフラット！？' },
  { command: 'hide', character: 'flat' },
  { command: 'show', character: 'yomi', portrait: 'normal1' },
  { speaker: 'ヨミ', portrait: 'normal1', text: 'ずいぶん傷だらけね。' },
  { command: 'hide', character: 'yomi' },
  { command: 'show', character: 'flat', portrait: 'dest01' },
  { speaker: 'アリス', portrait: 'normal1', text: '何があったの？' },
  { speaker: 'フラット', portrait: 'dest01', text: '星の傷を集めていたんだ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'それは知ってるわ。' },
  { speaker: 'フラット', portrait: 'dest01', text: '集める場所がなかったから。' },
  { speaker: 'フラット', portrait: 'dest01', text: 'だから僕が持っていた。' },
  { command: 'hide', character: 'flat' },
  { command: 'show', character: 'yomi', portrait: 'normal1' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '全部？' },
  { command: 'hide', character: 'yomi' },
  { command: 'show', character: 'flat', portrait: 'normal1' },
  { speaker: 'フラット', portrait: 'dest01', text: '全部。' },
  { command: 'wait', duration: 1000 },
  { speaker: 'フラット', portrait: 'dest02', text: 'これで・・・帰れるよ。' },
  { speaker: 'アリス', portrait: 'normal3', text: 'フラット！' },
  { command: 'fadeout' },
  { command: 'hide_all' },
  { command: 'hide', character: 'alice' },
  { command: 'hide', character: 'flat' },
  { command: 'dialog_hide' },
  { command: 'hide_all' },
  { command: 'background', value: 'novels/back15.jpg' },
  { command: 'wait', duration: 1000 },
  { command: 'fadein' },
  { command: 'wait', duration: 1000 },
  { speaker: '', portrait: '', text: 'フラットの身体が崩れ始める。\n光の粒が舞う。' },
  { speaker: '', portrait: '', text: '腕が崩れる。\n肩が崩れる。' },
  { speaker: '', portrait: '', text: '光が砕ける。\n星屑が飲み込まれる。' },
  { command: 'fadeout' },
  { command: 'wait', duration: 1000 },
  { command: 'background', value: 'novels/back10.jpg', position: 'bottom', positionMobile: '30% 0%' },
  { command: 'wait', duration: 1000 },
  { command: 'fadein' },
  { speaker: 'アリス', portrait: 'normal2', text: 'フラット・・・。' },
  { speaker: 'アリス', portrait: 'normal1', text: '帰るまでがパーティーって、誰か教えてくれなかったの？' },
  { speaker: 'アリス', portrait: 'normal1', text: 'それとも、最後の向こう側に「帰りのドア」があるのかしらね。' },
  { command: 'dialog_hide' },
  { command: 'bg_scroll', direction: 'down', speed: 200, loop: true },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 9,
  nextUrl:     '../index.html?select=1&storyStage=9',
});

NovelEngine.play(SCRIPT);