const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_alice11.png',
      normal2: 'novels/image_alice12.png',
      normal3: 'novels/image_alice13.png',
      normal4: 'novels/image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_nefa01.png',
      normal2: 'novels/image_nefa02.png',
      normal3: 'novels/image_nefa03.png',
      normal4: 'novels/image_nefa04.png',
      normal5: 'novels/image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg11.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '危ない・・・危ない・・・' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: '有栖', portrait: 'normal1', text: 'え、何？\nえ、誰？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '何かはわからない\n私はニーファ' },
  { speaker: '有栖', portrait: 'normal1', text: 'こんにちわ　ニーファ\n私は有栖' },
  { speaker: '有栖', portrait: 'normal2', text: 'あのでかい惑星は何？' },
  { speaker: 'ニーファ', portrait: 'normal2', text: 'あれはビッグポイント\nこっちとあっちの境界点' },
  { speaker: '有栖', portrait: 'normal1', text: 'こっち？あっち？' },
  { speaker: '有栖', portrait: 'normal2', text: '・・・どっち？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '僕、こっちとあっちをつなぎたい' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '有栖、協力して' },
  { speaker: '有栖', portrait: 'normal1', text: '助けてもらったから協力はしたいけど' },
  { speaker: '有栖', portrait: 'normal2', text: '何したらいいの？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '傷ついた話\n聞かせてほしい　' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '傷ついたこと\nある？' },
  { speaker: '有栖', portrait: 'normal1', text: 'いきなり何？' },
  { speaker: '有栖', portrait: 'normal2', text: '・・・まぁ、あるけど' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'よかった\n聞かせて' },
  { speaker: '有栖', portrait: 'normal1', text: '仲良かった友達がいたんだ' },
  { speaker: '有栖', portrait: 'normal2', text: 'その子がクラスで嫌われ始めて' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'なぜ？' },
  { speaker: '有栖', portrait: 'normal1', text: 'さあ？\n理由あったのかな' },
  { speaker: 'ニーファ', portrait: 'normal2', text: 'fmfm・・・' },
  { speaker: '有栖', portrait: 'normal1', text: '最初はみんな普通に話してた' },
  { speaker: '有栖', portrait: 'normal2', text: 'でも、一人減って\n二人減って' },
  { speaker: '有栖', portrait: 'normal1', text: '気付いたら誰も話さなくなってた' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '有栖は？' },
  { speaker: '有栖', portrait: 'normal1', text: '私は普通に話してた' },
  { speaker: '有栖', portrait: 'normal2', text: 'そのうち私も無視された' },
  { speaker: '有栖', portrait: 'normal3', text: 'その子からも' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '来た！' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '来た来た来た来た来たー！' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '傷が来たーーー！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 23,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=23',
});

NovelEngine.play(SCRIPT);