const CHARACTERS = {
  alice: {
    name: 'アリス',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_alice01.png',
      normal2: 'image_alice02.png',
      normal3: 'image_alice03.png',
    },
  },
  flat: {
    name: 'フラット',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_flat01.png',
      normal2: 'image_flat02.png',
      normal3: 'image_flat03.png',
      normal4: 'image_flat06.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'back01.jpg' },
  { command: 'bgm', value: 'bgm01.mp3' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.0rem' },
  { command: 'show', character: 'alice', portrait: 'normal1' },
  { speaker: 'アリス', portrait: 'normal1', text: '困ったわね。迷ってしまったわ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'それに・・・　ここはどこ？' },
  { speaker: 'アリス', portrait: 'normal1', text: '不思議の国じゃなさそうね。' },
  { command: 'show', character: 'flat', portrait: 'normal2' },
  { speaker: 'フラット', portrait: 'normal2', text: 'やあ！アリス！' },
  { speaker: 'アリス', portrait: 'normal2', text: '誰？' },
  { speaker: 'フラット', portrait: 'normal3', text: '失敬な。\n僕は「誰？」なんて名前じゃないよ。' },
  { speaker: 'フラット', portrait: 'normal1', text: '僕はフラット。\nよろしく、アリス。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'よろしく、フラット。\nところで、ここはどこなの？' },
  { speaker: 'フラット', portrait: 'normal1', text: '今のところは、まだここだよ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'それは見ればわかるわ。\n' },
  { speaker: 'フラット', portrait: 'normal1', text: 'よかった。見失っているかと思った。' },
  { speaker: 'アリス', portrait: 'normal1', text: '見失うほど広くないでしょう。' },
  { speaker: 'フラット', portrait: 'normal1', text: '広さは関係ないよ。\n昨日なんてスプーンを見失った星があった。' },
  { speaker: 'アリス', portrait: 'normal1', text: '星がスプーンを？' },
  { speaker: 'フラット', portrait: 'normal1', text: '逆だったかもしれない。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'どっちでもいいわ。ここは何なの？' },
  { speaker: 'フラット', portrait: 'normal1', text: '星牢の外側。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'じゃあ内側もあるのね。' },
  { speaker: 'フラット', portrait: 'normal1', text: 'もちろん。外側があるものは大体そうだ。' },
  { speaker: 'アリス', portrait: 'normal1', text: '少し安心したわ。' },
  { speaker: 'フラット', portrait: 'normal1', text: 'でも内側は外側より外側にある。' },
  { speaker: 'アリス', portrait: 'normal2', text: '今の安心を返して。' },
  { speaker: 'フラット', portrait: 'normal1', text: '難しいな。\n安心は一度使うと傷になるから。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'あなたの話、全部そうなの？' },
  { speaker: 'フラット', portrait: 'normal1', text: '全部じゃないよ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'どれが違うの？' },
  { speaker: 'フラット', portrait: 'normal1', text: '全部。' },
  { speaker: 'アリス', portrait: 'normal2', text: 'そう・・・。\n（頭がおかしくなりそうよ。）' },
  { speaker: 'アリス', portrait: 'normal1', text: 'あなたとはにパーティーには行けそうにないわね。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'だって話がちぐはぐなんだもの。' },
  { speaker: 'フラット', portrait: 'normal1', text: 'パーティー！いいね！' },
  { speaker: 'フラット', portrait: 'normal1', text: 'じゃあこれから【星の花嫁】を助けるパーティーをしよう。' },
  { speaker: 'アリス', portrait: 'normal1', text: '随分と物騒ね。' },
  { speaker: 'フラット', portrait: 'normal4', text: 'この、ピッケルと旗で、星の牢獄に捕らわれた【星の花嫁】を助けるだけさ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'ずいぶんと乱暴な説明ね。' },
  { speaker: 'フラット', portrait: 'normal1', text: '導入パートなんでそんなもんさ。' },
  { speaker: 'フラット', portrait: 'normal1', text: 'あとでツジツマがあえば、誰も気になんかしないさ。' },
  { speaker: 'アリス', portrait: 'normal2', text: '確かにね。' },
  { command: 'fadeout' },
  { command: 'hide_all' },
  { command: 'hide', character: 'alice' },
  { command: 'hide', character: 'flat' },
  { command: 'dialog_hide' },
  { command: 'background', value: 'back02.jpg', position: 'bottom' },
  { command: 'wait', duration: 2000 },
  { command: 'fadein' },
  { speaker: 'アリス', portrait: 'normal1', text: 'あれは？' },
  { speaker: 'フラット', portrait: 'normal1', text: 'あれが星牢。あの中に花嫁が囚われている。' },
  { speaker: 'フラット', portrait: 'normal1', text: 'それじゃあアリス！楽しんできて！' },
  { speaker: 'アリス', portrait: 'normal1', text: 'フラットは行かないの？' },
  { speaker: 'フラット', portrait: 'normal1', text: '僕はここにいないから、どこへも行けないんだ。' },
  { speaker: 'アリス', portrait: 'normal2', text: 'あら、そう。\nじゃあ楽しんでくるわ。' },
  { speaker: 'フラット', portrait: 'normal1', text: '良いパーティーを！' },
  { command: 'dialog_hide' },
  { command: 'bg_scroll', direction: 'down', speed: 200, loop: false },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   'images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 1, // novel01読了でステージ1を解放
  nextUrl:     '../index.html?select=1&storyStage=1',
});

NovelEngine.play(SCRIPT);