const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_alice11.png',
      normal2: 'novels/image_alice12.png',
      normal3: 'novels/image_alice13.png',
      normal4: 'novels/image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_nefa01.png',
      normal2: 'novels/image_nefa02.png',
      normal3: 'novels/image_nefa03.png',
      normal4: 'novels/image_nefa04.png',
      normal5: 'novels/image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg11.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い' },
  { speaker: '有栖', portrait: 'normal1', text: 'ハイハイ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: '乙女機能インストール中・・・ピピピ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'プププ\n' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'ポポポ' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'インストール完了' },
  { speaker: '有栖', portrait: 'normal1', text: 'おめでとう' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'あと５個' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '次は立ち直った話を聞きたい' },
  { speaker: '有栖', portrait: 'normal1', text: '一人じゃ無理だったかな' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '誰かいたの？' },
  { speaker: '有栖', portrait: 'normal1', text: 'うん' },
  { speaker: '有栖', portrait: 'normal2', text: 'エリカっていう高校生の女の子' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '有栖より大人？' },
  { speaker: '有栖', portrait: 'normal1', text: 'ずっとね' },
  { speaker: '有栖', portrait: 'normal2', text: '年齢も、生き方も' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '死に方も？\n' },
  { speaker: '有栖', portrait: 'normal1', text: '多分、、、ね' },
  { speaker: '有栖', portrait: 'normal2', text: '『優しい人って、傷つかない人じゃないよ』' },
  { speaker: '有栖', portrait: 'normal1', text: 'って言ってくれた' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'エリカも傷ついてた？' },
  { speaker: '有栖', portrait: 'normal1', text: 'そうかもね' },
  { speaker: '有栖', portrait: 'normal1', text: 'でも、エリカはね、' },
  { speaker: '有栖', portrait: 'normal2', text: '傷ついても、怖くはないんだって' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '有栖がいたから？' },
  { speaker: '有栖', portrait: 'normal1', text: '私じゃないよ' },
  { speaker: '有栖', portrait: 'normal2', text: 'でも、私はエリカがいたから' },
  { speaker: '有栖', portrait: 'normal1', text: '傷つくことは怖くない' },
  { speaker: '有栖', portrait: 'normal2', text: 'って思えるようになった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'どうして？' },
  { speaker: '有栖', portrait: 'normal1', text: '傷つかないために心を閉じるんじゃなくて、' },
  { speaker: '有栖', portrait: 'normal2', text: '傷ついても開ける心を持つんだって' },
  { speaker: '有栖', portrait: 'normal3', text: 'それで、吹っ切れたの' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '来た！' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '来た来た来た来た来たー！' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '再生が来たーーー！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 25,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=25',
});

NovelEngine.play(SCRIPT);