const CHARACTERS = {
  alice: {
    name: 'アリス',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_alice01.png',
      normal2: 'image_alice02.png',
      normal3: 'image_alice03.png',
      normal4: 'image_alice04.png',
    },
  },
  flat: {
    name: 'フラット',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_flat01.png',
      normal2: 'image_flat02.png',
      normal3: 'image_flat03.png',
    },
  },
  yomi: {
    name: 'ヨミ',
    position: 'right',
    defaultPortrait: 'normal',
    portraits: {
      normal1: 'image_yomi01.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'back01.jpg' },
  { command: 'bgm', value: 'bgm01.mp3' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.0rem' },
  { speaker: '', portrait: '', text: '崩壊したフラットはブラックホールとなり、' },
  { speaker: '', portrait: '', text: 'そのブラックホールも静かに収縮し、' },
  { speaker: '', portrait: '', text: '青く光る星屑を残して、' },
  { speaker: '', portrait: '', text: 'やがて消滅した。' },
  { speaker: '', portrait: '', text: '―――静寂。' },
  { command: 'show', character: 'alice', portrait: 'normal1' },
  { speaker: 'アリス', portrait: 'normal1', text: '・・・ここは？' },
  { command: 'show', character: 'yomi', portrait: 'normal1' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '不思議の国。' },
  { speaker: 'アリス', portrait: 'normal1', text: '帰ってきたの？' },
  { speaker: 'ヨミ', portrait: 'normal1', text: 'いいえ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'じゃあ違うの？' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '多分違わない。' },
  { speaker: 'アリス', portrait: 'normal2', text: 'どっちなのよ。' },
  { speaker: 'ヨミ', portrait: 'normal1', text: '不思議の国に地図を求めるほうが間違いよ。' },
  { command: 'hide', character: 'yomi' },
  { speaker: 'フラット', portrait: 'normal1', text: 'やぁ。' },
  { command: 'wait', duration: 1000 },
  { command: 'show', character: 'flat', portrait: 'normal1' },
  { speaker: 'アリス', portrait: 'normal1', text: '「やぁ」じゃないわよ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'パーティーは終わっちゃったわよ。' },
  { speaker: 'フラット', portrait: 'normal1', text: 'あれ、アリスだ。' },
  { speaker: 'アリス', portrait: 'normal1', text: '「アリスだ。」じゃないわよ。' },
  { speaker: 'アリス', portrait: 'normal2', text: '消滅したかと思ったわ。' },
  { speaker: 'フラット', portrait: 'normal1', text: '消滅はしたよ。' },
  { speaker: 'アリス', portrait: 'normal1', text: '・・・。' },
  { speaker: 'フラット', portrait: 'normal1', text: '・・・。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'じゃあ、なんでいるのよ。' },
  { speaker: 'フラット', portrait: 'normal3', text: '・・・' },
  { speaker: 'フラット', portrait: 'normal1', text: '道に迷ったからかな？' },
  { speaker: 'フラット', portrait: 'normal1', text: '納得した？' },
  { speaker: 'アリス', portrait: 'normal2', text: '全然。' },
  { command: 'fadeout' },
  { command: 'wait', duration: 1000 },
  { command: 'background', value: 'back12.png', position: 'bottom' },
  { command: 'wait', duration: 1000 },
  { command: 'fadein' },
  { speaker: 'フラット', portrait: 'normal1', text: 'じゃあ、そろそろ行こう。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'どこに？' },
  { speaker: 'フラット', portrait: 'normal1', text: 'わからないよ。' },
  { speaker: 'アリス', portrait: 'normal1', text: '「わからない」に行くの？' },
  { speaker: 'フラット', portrait: 'normal1', text: 'わかってきたね。' },
  { speaker: 'アリス', portrait: 'normal2', text: 'もういいわ。' },
  { speaker: 'アリス', portrait: 'normal1', text: '結局、フラットは何者だったワケ？' },
  { speaker: 'フラット', portrait: 'normal1', text: '僕？' },
  { speaker: 'フラット', portrait: 'normal1', text: '・・・。' },
  { speaker: 'フラット', portrait: 'normal3', text: '迷子だよ。' },
  { speaker: 'アリス', portrait: 'normal1', text: 'なにそれ。' },
  { speaker: 'アリス', portrait: 'normal4', text: 'フフッ。' },
  { command: 'wait', duration: 1000 },
  { command: 'hide', character: 'alice' },
  { command: 'hide', character: 'flat' },
  { command: 'dialog_hide' },
  { command: 'wait', duration: 5000 },
  { command: 'bg_scroll', direction: 'down', speed: 200, loop: false },
  { command: 'wait', duration: 5000 },
  { command: 'bgm_fade', duration: 2000 },
  { command: 'blackout' },
  { command: 'background', value: 'back13.png' },
  { command: 'title_card', title: 'STELLAR DELETE', text: '彼女たちの迷子は続く・・・。', duration: 3000 },
  { command: 'wait', duration: 3000 },
  { command: 'fg', value: 'back14.jpg', fit: 'contain' },
  { command: 'wait', duration: 1000 },
  { command: 'fadein' },
  { command: 'wait', duration: 3000 },
  { command: 'fadeout' },
  { command: 'wait', duration: 1000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   'images/',
  bgmPath:     '../sounds/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  nextUrl:     '../index.html',
});

NovelEngine.play(SCRIPT);