const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_alice11.png',
      normal2: 'image_alice12.png',
      normal3: 'image_alice13.png',
      normal4: 'image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_nefa01.png',
      normal2: 'image_nefa02.png',
      normal3: 'image_nefa03.png',
      normal4: 'image_nefa04.png',
      normal5: 'image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg11.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い' },
  { speaker: '有栖', portrait: 'normal1', text: '良い？　何が？' },
  { speaker: 'ニーファ', portrait: 'normal4', text: '乙女機能インストール中・・・ピピピ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'プププ\n' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'ポポポ' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'インストール完了' },
  { speaker: '有栖', portrait: 'normal1', text: 'インストール？\n乙女機能？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'つなぐために必要な機能' },
  { speaker: 'ニーファ', portrait: 'normal2', text: 'あと６個' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '次は犠牲になった話を聞きたい' },
  { speaker: '有栖', portrait: 'normal1', text: 'よくわかんないけど' },
  { speaker: '有栖', portrait: 'normal2', text: '傷ついた話の続き？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '続き　続き' },
  { speaker: '有栖', portrait: 'normal1', text: '周りから無視されるようになって、' },
  { speaker: '有栖', portrait: 'normal2', text: 'グループから外されたり、' },
  { speaker: '有栖', portrait: 'normal2', text: '有ること無いこと言われたりした' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '理不尽　理不尽' },
  { speaker: '有栖', portrait: 'normal1', text: '今ならそう思う' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '当時は？' },
  { speaker: '有栖', portrait: 'normal1', text: '大丈夫なふりしてた' },
  { speaker: '有栖', portrait: 'normal2', text: '全然大丈夫じゃなかった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '庇ってあげた子も？' },
  { speaker: '有栖', portrait: 'normal1', text: 'そう' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'なぜ' },
  { speaker: '有栖', portrait: 'normal1', text: 'その子も怖かったんだと思う' },
  { speaker: '有栖', portrait: 'normal2', text: 'だから弱音吐いちゃダメだと思った' },
  { speaker: '有栖', portrait: 'normal3', text: 'その子の方が辛そうだったから' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '来た！' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '来た来た来た来た来たー！' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '犠牲が来たーーー！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 24,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=24',
});

NovelEngine.play(SCRIPT);