const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_alice11.png',
      normal2: 'novels/image_alice12.png',
      normal3: 'novels/image_alice13.png',
      normal4: 'novels/image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_nefa01.png',
      normal1: 'novels/image_nefa02.png',
      normal1: 'novels/image_nefa03.png',
      normal1: 'novels/image_nefa04.png',
      normal1: 'novels/image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg04.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: '有栖', portrait: 'normal1', text: 'ここどこ？' },
  { speaker: '有栖', portrait: 'normal2', text: 'え？' },
  { speaker: '有栖', portrait: 'normal1', text: '待って待って待って。' },
  { speaker: '有栖', portrait: 'normal2', text: '登校中だったよね？' },
  { speaker: '有栖', portrait: 'normal1', text: 'え？' },
  { speaker: '有栖', portrait: 'normal2', text: '私、死んだ？' },
  { speaker: '', portrait: '', text: '周囲を見回す。\nどこまでも続く暗い宇宙。' },
  { speaker: '', portrait: '', text: '遠くに無数の光。\n上も下も分からない。' },
  { speaker: '有栖', portrait: 'normal1', text: 'いやいやいや。' },
  { speaker: '有栖', portrait: 'normal2', text: '死んだらスマホ持ってないでしょ。' },
  { speaker: '有栖', portrait: 'normal1', text: '・・・。' },
  { speaker: '有栖', portrait: 'normal2', text: 'あった。' },
  { speaker: '有栖', portrait: 'normal1', text: '圏外。' },
  { speaker: '有栖', portrait: 'normal2', text: 'ですよねー！\n知ってた！' },
  { speaker: '有栖', portrait: 'normal1', text: '宇宙だもん！' },
  { speaker: '有栖', portrait: 'normal2', text: 'なんで宇宙なんだよ！！' },
  { speaker: '有栖', portrait: 'normal3', text: '・・・ん？' },
  { command: 'fadeout' },
  { command: 'hide_all' },
  { command: 'hide', character: 'alice2' },
  { command: 'dialog_hide' },
  { command: 'background', value: 'novels/back22.jpg' },
  { command: 'se', value: 'gogogo.wav' },
  { command: 'wait', duration: 2000 },
  { command: 'fadein' },
  { speaker: '有栖', portrait: 'normal1', text: '星？' },
  { speaker: '有栖', portrait: 'normal2', text: 'デカくない？' },
  { speaker: '有栖', portrait: 'normal1', text: '待って待って。' },
  { speaker: '有栖', portrait: 'normal2', text: 'ちょっと待って。' },
  { speaker: '有栖', portrait: 'normal1', text: '惑星じゃん。' },
  { speaker: '有栖', portrait: 'normal2', text: '惑星来ることある！？' },
  { speaker: '有栖', portrait: 'normal1', text: '宇宙だから？' },
  { speaker: '有栖', portrait: 'normal3', text: 'そんなわけない。' },
  { command: 'dialog_hide' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 22,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=22',
});

NovelEngine.play(SCRIPT);