const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_alice11.png',
      normal2: 'image_alice12.png',
      normal3: 'image_alice13.png',
      normal4: 'image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'image_nefa01.png',
      normal2: 'image_nefa02.png',
      normal3: 'image_nefa03.png',
      normal4: 'image_nefa04.png',
      normal5: 'image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg11.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い' },
  { speaker: '有栖', portrait: 'normal1', text: '良かったわね' },
  { speaker: 'ニーファ', portrait: 'normal4', text: '乙女機能インストール中・・・ピピピ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'プププ\n' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'ポポポ' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'インストール完了' },
  { speaker: '有栖', portrait: 'normal1', text: '私の話が役に立ってよかったわ' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'あと４個' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '次はつながった話を聞きたい' },
  { speaker: '有栖', portrait: 'normal1', text: 'よくわかんないけど' },
  { speaker: '有栖', portrait: 'normal2', text: '続きでいいの？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い' },
  { speaker: '有栖', portrait: 'normal1', text: 'あの子の話' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '裏切った子' },
  { speaker: '有栖', portrait: 'normal1', text: '言い方' },
  { speaker: '有栖', portrait: 'normal2', text: 'その後' },
  { speaker: '有栖', portrait: 'normal1', text: 'ひたすら普通だった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '普通' },
  { speaker: '有栖', portrait: 'normal1', text: '無視もいつのまになくなって' },
  { speaker: '有栖', portrait: 'normal2', text: 'でも、' },
  { speaker: '有栖', portrait: 'normal1', text: 'あの子との距離だけが戻らなかった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '離れた？' },
  { speaker: '有栖', portrait: 'normal1', text: 'でも、嫌いになれなかった' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '理解不能' },
  { speaker: '有栖', portrait: 'normal1', text: 'だよね' },
  { speaker: '有栖', portrait: 'normal2', text: 'でもね、' },
  { speaker: '有栖', portrait: 'normal1', text: '楽しかった時間まで嘘になる' },
  { speaker: '有栖', portrait: 'normal2', text: 'そんな気がしたから' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '削除したらよかった' },
  { speaker: '有栖', portrait: 'normal1', text: '傷はね' },
  { speaker: '有栖', portrait: 'normal1', text: '捨てられないの' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '来た！' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '来た来た来た来た来たー！' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'つながりが来たーーー！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 26,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=26',
});

NovelEngine.play(SCRIPT);