const CHARACTERS = {
  alice2: {
    name: '有栖',
    position: 'left',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_alice11.png',
      normal2: 'novels/image_alice12.png',
      normal3: 'novels/image_alice13.png',
      normal4: 'novels/image_alice14.png',
    },
  },
  nefar: {
    name: 'ニーファ',
    position: 'right',
    defaultPortrait: 'normal1',
    portraits: {
      normal1: 'novels/image_nefa01.png',
      normal2: 'novels/image_nefa02.png',
      normal3: 'novels/image_nefa03.png',
      normal4: 'novels/image_nefa04.png',
      normal5: 'novels/image_nefa05.png',
    },
  }
};

const SCRIPT = [
  { command: 'background', value: 'plays/img_bg11.jpg' },
  { command: 'font', family: 'Kaisei Decol', sizePC: '2.0rem', sizeSP: '1.5rem' },
  { command: 'bgm', value: 'SND_12_bgm02.mp3' },
  { command: 'show', character: 'nefar', portrait: 'normal1' },
  { command: 'show', character: 'alice2', portrait: 'normal1' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '良い　良い' },
  { speaker: 'ニーファ', portrait: 'normal4', text: '乙女機能インストール中・・・ピピピ' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'プププ\n' },
  { speaker: 'ニーファ', portrait: 'normal4', text: 'ポポポ' },
  { speaker: 'ニーファ', portrait: 'normal3', text: 'インストール完了' },
  { speaker: '有栖', portrait: 'normal1', text: 'あと何個？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'あと３個' },
  { speaker: '有栖', portrait: 'normal1', text: '次は何の話？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '次は運命の話を聞きたい' },
  { speaker: '有栖', portrait: 'normal1', text: '運命か・・・' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '最初から決まっていた出会いとか' },
  { speaker: '有栖', portrait: 'normal1', text: '運命って、' },
  { speaker: '有栖', portrait: 'normal2', text: '冷たいものだと思ってた' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '信じてなかった？' },
  { speaker: '有栖', portrait: 'normal1', text: '信じるとかじゃなくて、' },
  { speaker: '有栖', portrait: 'normal2', text: '本当に運命だったかなんて、' },
  { speaker: '有栖', portrait: 'normal1', text: '誰にも証明できないでしょ？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: 'できない証明はないよ' },
  { speaker: '有栖', portrait: 'normal1', text: 'そうなの？' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '５６億光年たっても、わからない証明もあるけど' },
  { speaker: '有栖', portrait: 'normal1', text: 'できてないじゃん' },
  { speaker: '有栖', portrait: 'normal2', text: '・・・' },
  { speaker: '有栖', portrait: 'normal1', text: 'あの日、エリカに出会えたことが運命なら' },
  { speaker: '有栖', portrait: 'normal2', text: 'その出会いが、運命になったんじゃないかな' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '難解　難解' },
  { speaker: '有栖', portrait: 'normal1', text: '私にもわかんないよ' },
  { speaker: '有栖', portrait: 'normal2', text: 'でもね、' },
  { speaker: '有栖', portrait: 'normal1', text: '最初から答えが決まっているとか、' },
  { speaker: '有栖', portrait: 'normal2', text: 'そんなんじゃなくて、' },
  { speaker: '有栖', portrait: 'normal1', text: '出会いを、大切な意味に変えられるかどうか、' },
  { speaker: '有栖', portrait: 'normal2', text: '良い運命にできたかどうか、' },
  { speaker: '有栖', portrait: 'normal1', text: 'そのくらいのものだと思う' },
  { speaker: '有栖', portrait: 'normal2', text: 'そんな気がしたから' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '僕と出会ったことも？' },
  { speaker: '有栖', portrait: 'normal3', text: 'かもね' },
  { speaker: 'ニーファ', portrait: 'normal1', text: '来た！' },
  { speaker: 'ニーファ', portrait: 'normal2', text: '来た来た来た来た来たー！' },
  { speaker: 'ニーファ', portrait: 'normal3', text: '運命が来たーーー！' },
  { command: 'hide', character: 'alice2' },
  { command: 'hide', character: 'nefar' },
  { command: 'wait', duration: 2000 },
  { command: 'bgm_fade', duration: 2000 },
];

NovelEngine.init({
  characters:  CHARACTERS,
  imagePath:   '../assets/images/',
  bgmPath:     '../assets/audio/',
  sePath:      'se/',
  typingSpeed: 30,
  clickSE:     'click.wav',
  unlockStageOnComplete: 27,
  saveStageField: 'unlockedStage2',
  nextUrl:     '../index.html?select=1&storyStage=27',
});

NovelEngine.play(SCRIPT);